CXX=g++-4.9

CXXFLAGS=-std=c++14 -Wall -pedantic -D__ARM_PCS_VFP

DEPEND_FLAGS=-I/usr/include/c++/4.9/ \
	-I/usr/include/arm-linux-gnueabihf/c++/4.9/ \
	-I/usr/include/arm-linux-gnueabihf/ \
	-I/usr/lib/gcc/arm-linux-gnueabihf/4.9/include/